In [1]:
#Imports 
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split

In [4]:
Combine_Data = pd.read_csv("2021Combine.csv")
Combine_Data.head()

,Name,Pos,School,Height,Weight,Hands,Arms,Wingspan,40 Yd,10 Split,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,NaN,NaN,NaN,4.60,NaN,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,NaN,NaN,NaN,4.61,NaN,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,NaN,NaN,NaN,4.52,NaN,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,NaN,NaN,NaN,4.51,NaN,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,NaN,NaN,NaN,4.27,NaN,32.0,"10'3""",NaN,7.13,4.25

In [7]:
Combine_df = pd.DataFrame(Combine_Data)
Combine_df = Combine_df.drop(['Hands', 'Arms', 'Wingspan', '10 Split'], axis = 1)
Combine_df.head()

,Name,Pos,School,Height,Weight,40 Yd,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,4.60,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,4.61,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,4.52,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,4.51,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,4.27,32.0,"10'3""",NaN,7.13,4.25

In [12]:
WR_df = Combine_df.loc[Combine_df['Pos'] == 'WR']
WR_df.head()

,Name,Pos,School,Height,Weight,40 Yd,Vertical,Broad,Bench,3-Cone,Shuttle
0,Adam Krumholz,WR,Wisconsin,"6'0""",193.0,4.60,35.5,"9'10""",11.0,7.03,4.28
1,Adrian Hardy,WR,Louisiana Tech,"6'1""",205.0,4.61,37.5,"10'4""",12.0,6.96,4.50
2,Amari Rodgers,WR,Clemson,"5'9""",212.0,4.52,33.0,"10'1""",19.0,7.07,4.31
3,Amon-Ra St. Brown,WR,USC,"5'11""",197.0,4.51,38.5,"10'7""",20.0,6.88,4.17
4,Anthony Schwartz,WR,Auburn,"6'0""",186.0,4.27,32.0,"10'3""",NaN,7.13,4.25

In [15]:
WR_df = WR_df.fillna(0)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(WR_df)

                         Name Pos           School Height  Weight  40 Yd  \
0               Adam Krumholz  WR        Wisconsin   6'0"   193.0   4.60
1                Adrian Hardy  WR   Louisiana Tech   6'1"   205.0   4.61
2               Amari Rodgers  WR          Clemson   5'9"   212.0   4.52
3           Amon-Ra St. Brown  WR              USC  5'11"   197.0   4.51
4            Anthony Schwartz  WR           Auburn   6'0"   186.0   4.27
5                Antonio Nunn  WR          Buffalo  5'11"   204.0   4.50
8              Bailey Gaither  WR     San Jose St.   6'0"   188.0   4.45
10              Ben Skowronek  WR       Notre Dame   6'2"   220.0   0.00
11               Blake Proehl  WR    East Carolina   6'1"   186.0   4.47
14               Branden Mack  WR           Temple   6'5"   217.0   4.66
15              Brandon Smith  WR             Iowa   6'1"   218.0   4.62
17             Brennan Eagles  WR            Texas   6'3"   225.0   4.55
27           Connor Wedington  WR         Stanford   6'0"   196.0   4.47
29             Cornell Powell  WR          Clemson   6'0"   204.0   4.53
30           D'Wayne Eskridge  WR   West. Michigan   5'8"   190.0   4.38
31             Damon Hazelton  WR         Missouri      0     0.0   4.60
32              Damonte Coxie  WR          Memphis   6'2"   198.0   4.77
36                  Dax Milne  WR              BYU      0     0.0   4.54
37               Dazz Newsome  WR   North Carolina  5'10"   190.0   4.59
41            DeVontres Dukes  WR    South Florida   6'3"   216.0   4.81
42            Dez Fitzpatrick  WR       Louisville   6'1"   208.0   4.43
43              Dillon Stoner  WR     Oklahoma St.   6'0"   194.0   4.51
44                Dyami Brown  WR   North Carolina   6'0"   189.0   4.46
45                  Eli Stove  WR           Auburn  5'11"   194.0   4.54
47               Elijah Moore  WR      Mississippi      0     0.0   4.35
49                Frank Darby  WR      Arizona St.   6'0"   201.0   4.56
58       Ihmir Smith-Marsette  WR             Iowa   6'0"   181.0   4.43
59               Isaiah McKoy  WR         Kent St.   6'2"   200.0   4.68
62              Ja'Marr Chase  WR              LSU   6'0"   201.0   4.34
64               Jacob Harris  WR  Central Florida   6'5"   219.0   4.39
65              Jaelon Darden  WR      North Texas   5'7"   174.0   4.47
68                 Jalen Camp  WR     Georgia Tech   6'1"   226.0   4.48
74              Jaylen Harris  WR         Ohio St.   5'8"   170.0   4.77
78          Johnathon Johnson  WR         Missouri      0     0.0   0.00
79             Jonathan Adams  WR     Arkansas St.   6'2"   210.0   4.59
80             Jonathan Nance  WR         Missouri      0     0.0   0.00
81              Josh Blancato  WR     Georgia Tech   5'9"   182.0   4.55
82          Josh Imatorbhebhe  WR         Illinois   6'0"   218.0   4.53
87             Kadarius Toney  WR          Florida  5'11"   193.0   4.39
88               Kawaan Baker  WR    South Alabama   6'0"   210.0   4.44
93             Khalil McClain  WR             Troy   6'2"   214.0   4.70
100           Marlon Williams  WR  Central Florida  5'11"   209.0   4.63
101         Marquez Stevenson  WR          Houston  5'10"   180.0   4.48
105              Nico Collins  WR         Michigan   6'4"   215.0   4.43
113              Racey McMath  WR              LSU   6'2"   217.0   4.36
115  Ramaud Chiaokhiao-Bowman  WR     Northwestern   6'1"   204.0   4.78
116            Rashod Bateman  WR        Minnesota   6'0"   190.0   4.39
118                Riley Lees  WR     Northwestern  5'11"   192.0   4.47
119             Rondale Moore  WR           Purdue   5'7"   180.0   4.28
120              Sage Surratt  WR      Wake Forest   6'2"   209.0   4.66
124             Seth Williams  WR           Auburn   6'3"   211.0   4.49
126               Simi Fehoko  WR         Stanford   6'3"   222.0   4.44
128           Tamorrion Terry  WR      Florida St.   6'2"   207.0   4.44
129               Tarik Black  WR            Texas   6'2"   213.0   4.54
130      Terrace Marshall Jr.  WR              LSU   6'2"   205.0   4.40
133                 Tre Nixon  WR  Central Florida   6'0"   187.0   4.44
134                Tre Walker  WR     San Jose St.  5'10"   178.0   4.58
136             Trevon Grimes  WR          Florida   6'4"   220.0   4.49
141               Tutu Atwell  WR       Louisville   5'8"   155.0   4.42
142             Tylan Wallace  WR     Oklahoma St.  5'11"   194.0   4.48
143             Tyler Vaughns  WR              USC   6'1"   190.0   4.62
144            Warren Jackson  WR     Colorado St.   6'6"   219.0   4.68
145              Whop Philyor  WR          Indiana   5'9"   184.0   4.57

     Vertical   Broad  Bench  3-Cone  Shuttle
0        35.5   9'10"   11.0    7.03     4.28
1        37.5   10'4"   12.0    6.96     4.50
2        33.0   10'1"   19.0    7.07     4.31
3        38.5   10'7"   20.0    6.88     4.17
4        32.0   10'3"    0.0    7.13     4.25
5        33.5   10'0"   15.0    7.12     4.32
8        31.0   10'1"    9.0    7.07     4.39
10        0.0       0   13.0    0.00     0.00
11       36.0   10'6"   12.0    7.00     4.06
14       31.0    9'7"   11.0    7.13     4.37
15       39.5  10'10"    0.0    0.00     0.00
17       36.5   10'5"    0.0    6.93     4.42
27       38.5    9'9"   13.0    6.66     4.07
29       36.5   10'8"   16.0    7.03     4.21
30       35.0   10'4"    0.0    6.93     4.22
31       37.5       0    0.0    0.00     0.00
32       30.5   10'2"    4.0    6.92     4.45
36       31.0    9'6"   14.0    0.00     4.19
37       34.0   10'1"   12.0    7.38     4.38
41       33.0   10'2"   16.0    7.07     4.41
42       35.0       0    0.0    7.09     4.26
43       37.0   10'3"   16.0    6.96     4.13
44       35.0   10'8"   18.0    6.87     4.35
45       30.5   9'11"   14.0    7.34     4.40
47       36.0   10'1"   17.0    6.63     4.07
49       34.5    9'9"   19.0    7.05     4.25
58       37.0   10'4"    0.0    7.00     4.20
59       29.5    9'6"   12.0    7.09     4.36
62       41.0   11'0"    0.0    6.96     3.99
64       40.5   11'1"   15.0    6.54     4.31
65       35.5   10'2"    0.0    6.66     3.98
68       39.5   10'5"   29.0    7.00     4.14
74       30.5    9'1"    8.0    7.37     4.50
78        0.0       0    0.0    0.00     0.00
79       39.0   11'0"    0.0    7.04     4.38
80        0.0       0    0.0    0.00     0.00
81       32.0   10'4"   17.0    6.90     4.31
82       46.5   11'2"   24.0    7.10     4.38
87       39.5   11'4"    9.0    6.88     4.25
88       39.5   10'9"   21.0    7.42     4.41
93       32.0    9'6"   15.0    7.72     4.50
100      33.5   9'11"   14.0    0.00     4.57
101      33.0   10'2"    0.0    6.76     4.14
105      37.5   10'5"   14.0    6.78     4.29
113      34.0   10'4"    0.0    7.38     4.38
115      34.5   9'11"   11.0    6.78     4.20
116      36.0   10'3"    0.0    0.00     0.00
118      35.0   9'11"    7.0    6.78     4.16
119      42.5       0    0.0    6.65     4.06
120       0.0       0   18.0    0.00     4.25
124      37.0   10'4"   12.0    7.20     4.43
126      34.5   10'0"   16.0    6.78     4.26
128      32.5   10'6"   15.0    7.00     4.53
129      40.0   11'0"   15.0    6.91     4.26
130      39.0   10'5"   19.0    0.00     0.00
133      35.5   10'5"   18.0    6.81     4.27
134      28.0    9'5"    0.0    7.75     4.47
136      35.0   9'10"   15.0    6.98     4.28
141      33.0    9'9"    0.0    6.89     4.14
142      33.0    9'4"   11.0    6.97     4.25
143      31.5   10'0"    7.0    7.13     4.36
144      33.5   10'3"    0.0    7.81     4.53
145      31.0   10'0"   14.0    7.20     4.34